### ISSUE TITLE
Fazer a função que transforma o environ em uma matriz

### ISSUE THREAD

**Issue by Grsaiago** [leticia-paixao-wermelinger/minishell#2]
Fazer função que pegar o tamanho de uma matriz e depois criar uma função que transforma cada linha da environ em um nó de lista linkada conforme  a struct abaixo:

```C
typedef struct s_env
{
    char *key;
    char *value;
    struct s_env *next;
} t_env;
```

**Comment by leticia-paixao-wermelinger** [comment]
Function:
void    copy_env(t_command *command);
