### ISSUE TITLE
Fazer função que transforma o pipe em um caracter não printável

### ISSUE THREAD

**Issue by Grsaiago** [leticia-paixao-wermelinger/minishell#3]
A função deve pegar pipes que estão entre aspas e transformálos em um caracter não printável. Ex:

```sh
$> ls"|" | wc
```
vira 
```sh
$> ls<codigo do caracter não printável> | wc
```

* depois do split para separar em sentenças, tem que transformar o pipe de volta em um pipe.

**Comment by leticia-paixao-wermelinger** [comment]
Transformação de Pipe no meio de aspas (simples ou duplas) para caracter não printável: feito.
void    search_invalid_pipes(t_command *command);
