### ISSUE TITLE
Fazer uma my_getenv

### ISSUE THREAD

**Issue by Grsaiago** [leticia-paixao-wermelinger/minishell#4]
Reproduzir o comportamento da getenv, mas dessa vez procurando em uma lista linkada em que os nós sào

```C
typedef struct s_env
{
    char *key;
    char *value;
    struct s_env *next;
} t_env;
```

**Comment by leticia-paixao-wermelinger** [comment]
Função criada:
char    *my_getenv_by_list(const char *name, t_node *my_env);
Dentro do arquivo: env_builtins.c
